---
# Global default config for instance management.
global:
  # The address to your AMP instance web port.
  host: "http://localhost:8080"
  username: "username"
  password: "password"
  # Path to logs
  logging_path: "./"
  # Time in seconds for how often you want to ping the server.
  sample_interval: 300
  # Average rescue threshold in minutes: INTERVAL*THRESHOLD/60 (plus or minus ~0.95*INTERVAL/60).
  # How many pings during a server restart before rescuing the server.
  restart_threshold: 2
  # How many pings during a server start before rescuing the server.
  start_threshold: -1
  # How many pings during a server stop before rescuing the server.
  stop_threshold: -1

# Instances are identified using the instance name listed in the AMP web ui.
instances:
  # Leave the instance's config as {} for it to inherit the global config.
  Lobby:
    name: Lobby01
  # Any entry listed here will override the global config, and any unspecified entries will be pulled from the global config.
  CoolSMP:
    name: CoolSMP01
    id: 9jhb9t6
    start_threshold: 3